[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scan_plan"
version = "5.1.0"
description = "Advanced GUI for Cylinder Packing Strategy in high-resolution tomography."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "tifffile",
    "pyvista",
    "pyvistaqt",
    "pandas",
    "scipy>=1.15",
    "PyQt5",
    "pint"
]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = ["scan_plan"]

[tool.setuptools.package-data]
scan_plan = ["instrument_defaults.json"]

[project.scripts]
scan_planner = "scan_plan.cli:main"